#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.000000,
https://raw.githubusercontent.com/naveenland4/UTLive/main/assets/staytuned0.ts
#EXTINF:10.000000,
https://raw.githubusercontent.com/naveenland4/UTLive/main/assets/staytuned1.ts
#EXT-X-ENDLIST